package BitManipulation;

/**
 * @Number: #389. Find the Difference
 * @Descpription: Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * @Author: Created by xucheng.
 */
public class FindTheDifference {
    /**
     * bit manipulation
     * If we take XOR of two same bits, it will return 0
     * If we take XOR of zero and some bit, it will return that bit
     * so, a XOR b XOR a = a XOR a XOR b = 0 XOR b = b
     * time: O(n)
     * space: O(1)
     * @param s
     * @param t
     * @return
     */
    public char findTheDifference(String s, String t) {
       char c = 0;
       for (int i = 0; i < s.length(); i++)
           c ^= s.charAt(i);
       for (int i = 0; i < t.length(); i++)
           c ^= t.charAt(i);
       return c;
    }
}
